### ISSUE TITLE
Installation failed due to python's "--install-layout=deb" problem

### ISSUE THREAD

**Issue by nobuyuki-tomizawa** [lopsided98/nix-ros-overlay#1]
Thank you very much for your great package.

I've tried your package to run ROS on my Pop_OS! 18.10 (Ubuntu 18.10 variant), but unfortunately failed.

![Screenshot from 2019-08-30 11-56-13](https://user-images.githubusercontent.com/47237998/63990129-cddfd800-cb1d-11e9-85b0-ba7af6674c15.png)

The error message said 'error: option --install-layout not recognized'. This looks like a problem of original ROS/catkin problem.

So, I guess we can avoid this problem by adding '-DSETUPTOOLS_DEB_LAYOUT=OFF' to `catkin_make_isolated` invocation. (But I could not, because I'm novice for nix)

https://github.com/ros/catkin/issues/863
https://github.com/ros/catkin/issues/863#issuecomment-290392074

**Comment by lopsided98** [comment]
It looks like you are building without the Nix sandbox enabled (the build path would be `/build` instead of `/tmp/nix-build-ros-kinetic...` if you were using the sandbox). My guess is that catkin/setuptools is picking up on the fact that you are using Ubuntu and altering its build process in a way that Nix does not support.

I never use Nix without sandboxing, so I'm not going to put a ton of effort into making sure unsandboxed builds work, but I'll add the `-DSETUPTOOLS_DEB_LAYOUT=OFF` flag if you are able to verify that it fixes your problem. You should be able to add that flag here: https://github.com/lopsided98/nix-ros-overlay/blob/master/catkin-setup-hook/setup-hook.sh#L63

Personally, I would recommend that you enable sandboxed/multi-user Nix if you can, as it will avoid lots of similar issues in the future.
