### ISSUE TITLE
rviz and ogre

### ISSUE THREAD

**Issue by acowley** [lopsided98/nix-ros-overlay#154]
I recently updated to try out fixes to issues we've discussed, and found that `rviz` from `noetic` was segfaulting for me.

```
$ rviz
[ INFO] [1638366907.314265721]: rviz version 1.14.10
[ INFO] [1638366907.314295955]: compiled against Qt version 5.15.3
[ INFO] [1638366907.314306657]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1638366907.323839132]: Forcing OpenGl version 0.
[ INFO] [1638366907.593809008]: Stereo is NOT SUPPORTED
[ INFO] [1638366907.593875508]: OpenGL device: AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.42.0, 5.15.3, LLVM 13.0.0)
[ INFO] [1638366907.593908287]: OpenGl version: 4.6 (GLSL 4.6) limited to GLSL 1.4 on Mesa system.
Segmentation fault (core dumped)
```

Using `gdb`, I found that the segfault was coming from `Ogre`, and eventually found that if I built `rviz` against `ogre` from `nixpkgs` (i.e. version 1.12.1) it worked.

I have two questions stemming from this:
- Can anyone else reproduce the segfault?
- What's the best way to override a dependency?

Regarding the second question, I have a `flake.nix` that defines a `devShell` that includes `rviz`. I had hoped that including `(rviz.override { ogre1_9 = pkgs.ogre; })` rather than `rviz` would work, but that override did not have the desired effect (the `rviz` executable still reported being compiled against `ogre` 1.9.0). To get things working, I pointed the flake input to a local checkout of this repo in which I made the change from `ogre1_9` to `ogre`. Is there a way to more easily override packages in a downstream nix definition like this?

Thank you again for this wonderful project!

**Comment by lopsided98** [comment]
I haven't looked into this yet, but my guess is that it is caused by the Boost 1.73 upgrade. Ogre links against 1.69, and bad things happen if there are two versions of Boost in the same address space. Ogre 1.12 doesn't link against Boost, which makes the problem go away. I'm running into a similar problem with Gazebo.

As for why overriding rviz didn't work, my guess is that something else pulled in rviz (the un-overridden version) as a propagated build input and that one ended up first in `PATH`.
