### ISSUE TITLE
Faster CI?

### ISSUE THREAD

**Issue by wentasah** [lopsided98/nix-ros-overlay#510]
Hi @lopsided98 ,

if I understand correctly, you build all ROS packages on GitHub runners and aarch64-linux packages are built via qemu. This must take very long time. At our university, I've got a few powerful servers, whose power I could donate to building ROS packages. Specifically, I have an 80-core aarch64-linux machine and a 32-core x86_64-linux machine. Would you be interested in using these to speed-up development in this repo?

I see several possibilities how to use them. The simplest one, which can be working very quickly, is that the servers can be used as nix remote builders. Either for CI running on GitHub, or even for you personal Hydra (I think you have one somewhere).  Another option would be to run Hydra (or other CI system) on those servers to and integrate it in this repo.

Let me know what do you think and we can then discuss details such as security, trustworthiness etc.

**Comment by lopsided98** [comment]
We do need better CI, since right now the GitHub Actions build is almost completely broken. I think the builders are running out of memory. I can try further reducing the number of jobs, but then I think it will still run into the maximum build time limit.

I do build this overlay on my private Hydra instance, but I'd like to keep it private since it builds a lot of other stuff as well.

Adding remote builders to the GitHub Actions CI is a possibility, but it would put you and anyone else with admin access to the build servers in a position of trust, and even if this is clearly documented, that doesn't mean that existing users would necessarily be comfortable with it.

In fact, I should probably make it more clear in the documentation that by using the binary cache, you are effectively giving me code execution on your machine (even root privileges in some cases). There may be a false sense of security because the packages are built on GitHub Actions, but this is moot because I control the Cachix private key.
