### ISSUE TITLE
tf2-geometry-msgs/default.nix:5:1 called without required argument 'orocos-kdl'

### ISSUE THREAD

**Issue by werner291** [lopsided98/nix-ros-overlay#73]
Hello!

First of all, thank you so much for going through the trouble of building this overlay, installing Gazebo was very easy.

However, when trying to install `desktop` and `desktop-full` from noetic, I get this error:

error: anonymous function at /nix/store/arjab8nn57wlpi8rz0dm3lvcighp09km-source/distros/noetic/tf2-geometry-msgs/default.nix:5:1 called without required argument 'orocos-kdl', at /nix/store/8wi9lc6asmh74yng3k7cnx729m47pj9s-nixos-20.09.2382.ca119749d86/nixos/lib/customisation.nix:69:16

**Comment by lopsided98** [comment]
I can't reproduce this specific problem. Are you perhaps specifying a custom version of nixpkgs that doesn't have https://github.com/NixOS/nixpkgs/pull/97998?

On the other hand, I don't expect the `desktop` or `desktop-full` package sets to work. There are packages in them that are missing dependencies in nixpkgs or just otherwise don't build with Nix right now. In general you are better off just adding the specific packages you need to the shell.
