### ISSUE TITLE
wrapQtAppsHook needed for any Qt-based apps in latest nixpkgs

### ISSUE THREAD

**Issue by 3noch** [lopsided98/nix-ros-overlay#89]
Using latest nixpkgs today exposed a big change that nix-ros-overlay will need to handle somehow: Qt-based packages will now need to depend on `qt5.wrapQtAppsHook` or specify that they don't want wrapping. I'm not sure if there's any harm in just adding the dependency across the board. But this might require changes at the level of generating the nix expressions for a distro.

**Comment by lopsided98** [comment]
I'm aware of this problem and have been trying to figure out a solution. In the staging branch I added manual wrapping to some important packages, but there are really too many to do by hand.

I could just add `dontWrapQtApps = true` by default, which would bring things back to how they were before (ie. everything builds fine but non-overridden Qt apps are broken at runtime), but certainly isn't optimal. I thought about adding `wrapQtAppsHook` to the Qt rosdep keys, but that really isn't right either because it should be in `nativeBuildInputs`, although it might work when `strictDeps = false`. Also, many packages need manual calls to `wrapQtApp` because they have binaries in `lib`.

**Comment by 3noch** [comment]
Instead of changing distro generation, could you change `buildRosPackage` to automatically apply the necessary changes, at least in a majority of cases? I can imagine detecting dependencies on qt and adding the wrapQtAppsHook dependency automatically. For binaries in `lib` you might be able to write a script that dynamically applies the wrapping when it detects the need for it.

**Comment by lopsided98** [comment]
As you may have noticed, I decided to just set `dontWrapQtApps = true` by default a while ago. I have been unable to come with a reasonable method to do what you describe, and I think manually fixing things as needed is not too big of a deal. There are already a million other things that cause packages to need manual intervention anyway.
